### ISSUE TITLE
Checking against package.json

### ISSUE THREAD

**Issue by jareware** [parshap/check-node-version#1]
Something that would be useful:

    $ check-node-version --package

which would check that the node environment matches the `engines` spec of the package.json

What do you think?

**Comment by parshap** [comment]
This sounds useful. Can check the `npm` version from engines spec too. Interested in submitting a PR? I'm happy to help.

**Comment by jareware** [comment]
My proposed changes are in #2 and #3 (sorry for the separate PR's).
