### ISSUE TITLE
NPM using local version from node_modules not global version

### ISSUE THREAD

**Issue by bastienmoulia** [parshap/check-node-version#12]
I just start to use check-node-version and i notice that my NPM version (5.0.3) is not the same as the version displayed by check-node-version (3.10.10).

I probably had NPM version 3 before moving to nodeJS 8.

![image](https://user-images.githubusercontent.com/686196/27444429-a3880928-5776-11e7-8b09-2564a7525186.png)

**Comment by bastienmoulia** [comment]
I think this bug is due to another npm package in my *node_modules* with version 3.

This version is required by npm-check-updates on https://github.com/tjunnone/npm-check-updates/blob/master/package.json#L59

So is it a way to force using the global npm version ?

**Comment by parshap** [comment]
It looks like `check-node-version` is returning a different version number than when you run `npm -v`. That is unexpected. Are you saying `check-node-version` is getting the version of an npm installation in `node_modules` (by running `node_modules/.bin/npm`)? I wasn't able to reproduce that by installing npm-check-updates and running `check-node-version`. Any more information would be helpful.

**Comment by gregtillbrook** [comment]
I just hit the same problem on a project that had `npm-install-version` installed. The version from manually running 'npm -v' in the CLI was different from that returned by exec.

**Comment by rasenplanscher** [comment]
I just had a look at this: interestingly, the behavior is dependent on how the script is called.

After `npm i --save-dev npm@3.10`, I get this output in the `check-node-version` directory:
```ps
% node ./bin.js --print
node: 11.12.0
npm: 6.7.0
npx: 6.7.0
yarn: not installed

% npx ./bin.js --print
node: 11.12.0
npm: 3.10.10
npx: 6.7.0
yarn: not installed
```

With `node`, I get the global version, with `npx` I get the local version. I'm not sure how to work around this right now, but it might be helpful to others hitting on this issue.
