### ISSUE TITLE
Add NPX support

### ISSUE THREAD

**Issue by bastienmoulia** [parshap/check-node-version#13]
It would be nice to add support for [NPX](https://www.npmjs.com/package/npx) recently include with NPM 5.2.0.
See http://blog.npmjs.org/post/162869356040/introducing-npx-an-npm-package-runner

**Comment by parshap** [comment]
I'm open to including npx -- would you be interest in sending a pr?

**Comment by karfau** [comment]
For me running `npx check-node-version --package` works perfectly as a `preinstall` script.
Not sure what @bastienmoulia wanted to request.

**Comment by parshap** [comment]
Maybe he meant checking for a specific version of `npx`? But I suppose checking the version of `npm` is a good enough proxy?

**Comment by karfau** [comment]
I see, that would not be to hard...
