### ISSUE TITLE
Add sample code for API usage

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [parshap/check-node-version#16]
The link to index.js is nice, but seeing sample could would be easier to onboard with.

**Comment by parshap** [comment]
Yes, this would be great! Would you you have any interest in writing up some documentation and submitting a PR?

Also, just curious but what's your use case for using the API as opposed to the CLI?

**Comment by JoshuaKGoldberg** [comment]
My team at work has a `setup.js` script that sets up git hooks with `fs`, prints some happy message with `chalk`, and checks the system for being good (such as having a valid Node version). It's all stuff technically doable on the command-line but we support *Nix and Windows development boxes. JS gives a nice common language.
