### ISSUE TITLE
Add TypeScript typings?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [parshap/check-node-version#17]
It would be great if this shipped with TypeScript typings (or were even written in TypeScript!). That way we'd get better editor auto-completion in VS Code and/or when using TypeScript.

https://github.com/DefinitelyTyped/DefinitelyTyped/

I can send a PR with an index.d.ts unless directed otherwise. I'd be willing to convert to TS also.

**Comment by parshap** [comment]
I'm not too keen on having this written in TypeScript since it increases the barrier-of-entry for contributors, but I'm totally open to having type definitions included.
