### ISSUE TITLE
Testing against a version with a trailing 0 strips trailing zero (e.g.: 8.10)

### ISSUE THREAD

**Issue by kweij** [parshap/check-node-version#27]
Using `minimist()` to process the arguments causes an argument such as "8.10" to be interpreted as "8.1", stripping the trailing (but significant!) 0 from the version.

Testing against node version 8.10 will fail, because it erroneously gets tested against 8.1. I've traced this error back to the usage of `minimalist` in `bin.js` but I can't fix this - so sadly no PR.

**Comment by parshap** [comment]
Thank you for the report and trouble shooting. I'll try to take a look at this ASAP.
