### ISSUE TITLE
node versions in .travis.yml and appveyor.yml

### ISSUE THREAD

**Issue by rasenplanscher** [parshap/check-node-version#31]
`.travis.yml` and `appveyor.yml` list node versions 4, 6, 8, 9 – is that intentional and up-to-date?
My guess is that stable + latest is meant to be listed, which would at present be 4, 6, 8, 10, 11.
Since I don't have experience with either tool, I don't want to make this change without asking first.

**Comment by parshap** [comment]
Nope, it's definitely outdated. Yes, we should add the most recent version to both!
