### ISSUE TITLE
Using npx to run check-node-version fails since 4.0.0

### ISSUE THREAD

**Issue by karfau** [parshap/check-node-version#32]
**Steps to reproduce:**
run `npx check-node-version@4.0.0 --package`
(instead of adding the explicit version you can also add `--ignore-existing` to make sure npx doesn't use a version from a cache)

**Output**:
```
npx: installed 13 in 1.831s
/home/karfau/.npm/_npx/18612/bin/check-node-version: line 1: syntax error near unexpected token `'./gatekeeper''
/home/karfau/.npm/_npx/18612/bin/check-node-version: line 1: `require('./gatekeeper');'
```

**Workaround** (for people that use `npx check-node-version --package` e.g. in a `preinstall` script):

fix the version to use in your script to 3.3.0 like this:
`npx check-node-version@3.3.0 --package`

**Comment by paulmelnikow** [comment]
This is reproducible without npx, through an ordinary install:

https://circleci.com/gh/badges/shields/53136

**Comment by karfau** [comment]
> This is reproducible without npx, through an ordinary install:
> 
> https://circleci.com/gh/badges/shields/53136

Interesting, since it has a slightly different error message, you are using `run-s` to launch it in your `postinstall` script, which is coming from [`npm-run-all`](https://github.com/mysticatea/npm-run-all/blob/HEAD/docs/run-s.md). So this is using another wrapper around npm.

When I just setup a new project, install `check-node-version` locally (configure `engines` in `package.json`) and run it using `node node_modules/.bin/check-node-version --package` it doesn't fail that way.

**Comment by paulmelnikow** [comment]
Right, absent a shebang line, the program is run by your current shell. This is the message in our CI:

```
/home/circleci/project/node_modules/.bin/check-node-version: 1: /home/circleci/project/node_modules/.bin/check-node-version: Syntax error: word unexpected (expecting ")")
```

When I ran it locally I think I got the same message you're seeing.

**Comment by karfau** [comment]
yes, that't also the difference compared to earlier versions:
in version 3.3.0 the bin file started with `#!/usr/bin/env node`
which is the [requirement for binaries from npm packages](https://docs.npmjs.com/files/package.json#bin) (It is mentioned in the last sentence.
SO it is actually the last commit to master that moved the shebang into cli.js.
