### ISSUE TITLE
node 6 support

### ISSUE THREAD

**Issue by jareware** [parshap/check-node-version#5]
```
$ n 5.5.0
$ node --version
v5.5.0
$ ./node_modules/.bin/check-node-version --node ">=5 <6"
node: v5.5.0
npm: v3.3.12
$ n 6.3.1
$ node --version
v6.3.1
$ ./node_modules/.bin/check-node-version --node ">=6 <7"
(node:14219) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
$ echo $?
1
```

Ideas?

**Comment by parshap** [comment]
I can't seem to reproeduce this...

```
$ node --version
v6.3.1
$ check-node-version --node '>=6 <7'
node: v6.3.1
npm: v3.10.3
$ echo $?
0
```

Maybe you need an `npm rebuild` or fresh `npm install` after changing versions?

**Comment by jareware** [comment]
Happens consistently for me, also tried with `v6.4.0`, and `rm -rf node_modules && npm install`.

**Comment by jareware** [comment]
Ah, got it, it's that

    (node:14219) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

which is written to `stderr`.

**Comment by jareware** [comment]
`npm update -g npm` resolved the warning, and thus also made the issue go away.

I'm honestly not sure what the sensible fix would be in `check-node-version` to tolerate `stderr` output here, so feel free to close if you're not sure either.

**Comment by parshap** [comment]
Thanks. I think I understand what the problem was. [I've made a change to try and improve the error output.](https://github.com/parshap/check-node-version/commit/69e19e8faff004f9ce6b46b4305bed7b60afebba) Now you would see something like:

```
$ check-node-version
Command failed: "npm --version"
(node:14219) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

**Comment by jareware** [comment]
Very nice, thanks!
