### ISSUE TITLE
Add support for pnpm

### ISSUE THREAD

**Issue by drtyh2o** [parshap/check-node-version#50]
This is a very useful tool. We recently switched to using [pnpm](https://pnpm.io/). Would it be possible to add support for this package manger? `pnpm --version`

**Comment by parshap** [comment]
Yes, I'd be happy to accept a PR for that. It should be relatively easy to add support for a new tool.

**Comment by drtyh2o** [comment]
I got a little bit lost trying to figure out how the tests work. I would have to spend some time to understand those, but it only took a few minutes to add support for `pnpm` to the CLI.

**Comment by parshap** [comment]
I think you would need to mainly replicate these type of test:
https://github.com/parshap/check-node-version/blob/6f8fc3fd094c308e635cca4fb73b18333d72ff43/__tests__/index.js#L116-L145

You will also need to add some constants to _setup.js and _versions.js. Feel free to send a PR with your attempt, or even without tests, and that can be a good starting point.
